### ISSUE TITLE
Верстка main_layout 

### ISSUE THREAD

**Issue by arapovavikka** [arapovavikka/Procrastination#1]
Необходимо сделать верстку основного экрана в xml.
Элементы на экране:
- Layout: TextView, Switch
- Layout: TextView, Button
- Layout: 5 Buttons
- Layout: TextView, TextView 
- Layout: TextView, TextView 

Примерная разбивка - можно сделать и иначе.

**Comment by arapovavikka** [comment]
Дизайн со всеми размерами в [Figma](https://www.figma.com/file/kwCUqyU6FlcfvqPEfaHYkB/Material-Design-Theme-Kit-(Copy)-(Copy)?node-id=18804%3A29379)

![main_layout_figma](https://user-images.githubusercontent.com/11668995/56340827-ce558300-61bb-11e9-8155-0ce83e825bc7.JPG)

**Comment by GrigoriK** [comment]
Взял в работу.
