### ISSUE TITLE
Верстка: 2 экрана shake_settings_layout

### ISSUE THREAD

**Issue by arapovavikka** [arapovavikka/Procrastination#19]
Дизайн со всеми размерами в [Figma](https://www.figma.com/file/kwCUqyU6FlcfvqPEfaHYkB/Material-Design-Theme-Kit-(Copy)-(Copy)?node-id=18948%3A30432)

Нужно сверстать два таких экрана. Сейчас в приложении есть экраны с паролем - тут действовать аналогично и использовать те же стили для элементов. 
![Снимок](https://user-images.githubusercontent.com/11668995/57807160-47b7a580-7769-11e9-8a26-ab4ad0700ca2.PNG)

Внимание - если смотреть на правый экран, то там есть картинка из нескольких слоев. И вроде как в фигме оно повернуто на какой-то угол. В коде не надо поворачивать и придумывать изварт - я проверила, картинка должна нормально выгружаться. Если что я все равно верстку просматриваю и могу поправить)

**Comment by kristinatr** [comment]
картинки нет, скачать можно только слои по отдельности
