### ISSUE TITLE
Верстка overlay_layout

### ISSUE THREAD

**Issue by arapovavikka** [arapovavikka/Procrastination#2]
Необходимо сделать верстку экрана-блокировщика в xml.
Элементы на экране: Layout: TextView, TextView, Button
Примерная разбивка - можно сделать и иначе.

**Comment by arapovavikka** [comment]
Дизайн со всеми размерами в [Figma](https://www.figma.com/file/kwCUqyU6FlcfvqPEfaHYkB/Material-Design-Theme-Kit-(Copy)-(Copy)?node-id=18804%3A29379)

![overlay_layout_figma](https://user-images.githubusercontent.com/11668995/56340760-92222280-61bb-11e9-8e8b-63c7cfbe62af.JPG)

**Comment by kristinatr** [comment]
беру в работу
