### ISSUE TITLE
Заменить иконку в приложении

### ISSUE THREAD

**Issue by arapovavikka** [arapovavikka/Procrastination#9]
В [Figma](https://www.figma.com/file/kwCUqyU6FlcfvqPEfaHYkB/Material-Design-Theme-Kit-(Copy)-(Copy)?node-id=18804%3A29379) появилась иконка приложения -> добавьте ее пожалуйста!

**Comment by kristinatr** [comment]
сделано

**Comment by arapovavikka** [comment]
@kristinatr спасибо!
